### PR TITLE
Saved extra attribute options

### PR DESCRIPTION
**Pull request by kobsy**
This allows for extra options or flags to be passed to an attribute and consumed by an added presenter when preparing output

### CODE REVIEW

**Comment by boblail** [comment]
What's an example of how you would use this? Can you paste in a code snippet of what client code that uses this feature might look like?

**Comment by kobsy** [comment]
Sure! If, say, we were using `PluckMap::Presenter` to export to a JSON:API-type structure, it would be useful to designate attributes you might want to pull out from the `attributes` into `relationships`. E.g.,

```ruby
PluckMap::Presenter.new do
  id
  type "whatevers"
  category_id as_relationship: true
end
```

A JSON:API presenter could then filter out all `options[:as_relationship]` attributes when building the `attributes` hash, and then use all the `as_relationship` attributes to build the `relationships` hash without having to loop through all the records a second time to extract the `_id` attributes from the `attributes` hash.

I thought an explicit flag would be the better route than simply having a JSON:API presenter try to infer relationships (say, by assuming `type_id` is a relationship) as the flag would allow both JSON:API relationships _and_ including an `_id` as a regular attribute.

**Comment by boblail** [comment]
🤔 

So we sometimes define a `PluckMap::Presenter` and then use it with more than one `to_format` method. (In Members, for example, `Export::BasePresenter` constructs one presenter but then calls either `to_csv` or `to_xlsx` on it.)

If we want that to be a feature of the Pluck-Map pattern, then `as_relationship: true` might be more of a concern of the `to_json_api` method than the Pluck-Map DSL.

I'm not _sure_ if I even agree with what I'm saying, but: what would the code look like if

   1. `to_json_api` inferred relationships from the ActiveRecord models themselves?
   2. You passed that information into `to_json_api`?

In the first case, would it get some false positives? Are there cases where a model has a `belongs_to` association (not just a field that ends in `_id`) but we _don't_ want to present that as a relationship?

In the second case, what would that look like? `.to_json_api(relationships: %w{category})`

**Comment by kobsy** [comment]
In the first case, we would certainly get false-positives. For example, in LSB we will pass `shared_role_id` as an attribute instead of a full-blown relationship..

I don't dislike your proposed API for the second case. I think it would make inference and extraction from the attributes possible. If it truly is a concern only of `to_json_api`, I think the second approach is the way to go.

**Comment by kobsy** [comment]
Ended up going a different direction and not needing this PR after all.

**Pull request closed without merging**
